version = "2.0"

watch_list = ["book/src/**/*.md"]

[[languages]]
name = "Rust"
identifiers = ["rust", "rs"]
comment = { open = "//" }

[[languages]]
name = "Lua"
identifiers = ["lua"]
comment = { open = "--" }

[[languages]]
name = "TOML"
identifiers = ["toml"]
comment = { open = "#" }
