[project]
name        = "moonjson"
version     = "0.1.0"
license     = "MIT"
description = "A tiny pure-Lua JSON encoder/decoder"
channels    = ["conda-forge"]

[dependencies]
lua = ">=5.4,<5.5"

[build]
script = "build.lua"
noarch = true
