site_name: The Rattler Book
site_url: https://prefix-dev.github.io/rattler-book/
site_description: Building a package manager with rattler
docs_dir: src
site_dir: book

theme:
  name: material
  logo: assets/pixi-logo.svg
  favicon: assets/pixi-logo.svg
  palette:
    - scheme: default
      primary: custom
      accent: amber
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: custom
      accent: amber
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  font: false
  features:
    - navigation.instant
    - navigation.sections
    - navigation.expand
    - navigation.top
    - navigation.footer
    - content.code.copy
    - content.code.annotate
    - search.suggest
    - search.highlight
    - search.share
    - toc.integrate

nav:
  - Introduction: index.md
  - Building a Package Manager:
    - 1. What Is a Package Manager?: ch01-what-is-a-package-manager.md
    - 2. Setting Up the Project: ch02-project-setup.md
    - 3. The init Command: ch03-init.md
    - 4. The search Command: ch04-search.md
    - 5. The add Command: ch05-add.md
    - 6. The lock Command: ch06-lock.md
    - 7. The install Command: ch07-install.md
    - 8. Shell Hooks: ch08-shell-hook.md
    - 9. The run Command: ch09-run.md
    - 10. The build Command: ch10-build.md
  - Rattler and Conda Deep Dives:
    - The conda Package Format: deep-dive-package-format.md
    - Virtual Packages: deep-dive-virtual-packages.md
    - The Networking Stack: deep-dive-networking.md
    - The resolvo SAT Solver: deep-dive-resolvo.md
    - Overview of the rattler crates: deep-dive-crate-ecosystem.md

extra_css:
  - stylesheets/extra.css

plugins:
  - search
  - entangled
  - redirects:
      redirect_maps:
        'introduction.md': 'index.md'
        'ch06-install.md': 'ch07-install.md'
        'ch07-the-lock-file.md': 'ch06-lock.md'
        'ch08-shell.md': 'ch08-shell-hook.md'
  - panzoom:
      full_screen: true
  - print-site

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - attr_list
  - def_list
  - admonition
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - toc:
      permalink: true
  - tables
  - footnotes
